### PR TITLE
Maven enforcer plugin: Add support for Changed, Unmerged, Unknown git file filters

### LINKED ISSUE #1109: Copyright enforcer fails with file type changed
When changing the file type of a file (E.g. moving a file and replacing it with a symlink) the git log contains a line that starts with `T`.

E.g.

```
T       hols/oci-devops/init/locals.tf
T       hols/oci-devops/init/terraform.tfvars
T       hols/oci-devops/init/variables.tf
M       hols/oci-devops/main/destroy.sh
M       hols/oci-devops/main/get.sh
T       hols/oci-devops/main/locals.tf
T       hols/oci-devops/main/terraform.tfvars
T       hols/oci-devops/main/variables.tf
```

Exception:

```
Caused by: io.helidon.build.maven.enforcer.EnforcerException: Could not parse line T	hols/oci-devops/init/locals.tf
    at io.helidon.build.maven.enforcer.GitCommands.gitOp (GitCommands.java:330)
    at io.helidon.build.maven.enforcer.GitCommands.gitTracked (GitCommands.java:97)
    at io.helidon.build.maven.enforcer.FileFinder.findFiles (FileFinder.java:89)
    at io.helidon.build.maven.enforcer.EnforcerMojo.execute (EnforcerMojo.java:189)
```

The git command executed by [GitCommands.gitTracked](https://github.com/helidon-io/helidon-build-tools/blob/7bd17f3c960d9d8ee4de56d4b879fe13e0b436c7/maven-plugins/enforcer-maven-plugin/src/main/java/io/helidon/build/maven/enforcer/GitCommands.java#L75) is:

```shell
git log --pretty=%cd --date=short --name-status --reverse
```

The help of `--name-status` shows this:
```
See the description of the --diff-filter option on what the status letters mean.
```

The help of `--diff-filter` shows this:
```
Select only files that are Added (A), Copied (C), Deleted (D), Modified (M), Renamed (R), have their type (i.e. regular file, symlink, submodule, ...) changed (T), are Unmerged (U), are Unknown (X),
```

The code that parses the output is here: https://github.com/helidon-io/helidon-build-tools/blob/7bd17f3c960d9d8ee4de56d4b879fe13e0b436c7/maven-plugins/enforcer-maven-plugin/src/main/java/io/helidon/build/maven/enforcer/GitCommands.java#L314

It's missing `T`, `U` and `X`.

### PR DESCRIPTION
**Pull request by tvallin**
Fixes #1109

### CODE REVIEW

File: common/common/src/main/java/io/helidon/build/common/FileUtils.java [hunk 1]
```diff
@@ -1139,4 +1142,21 @@ public static URL urlOf(Path path) {
...
     }
+
+    /**
+     * Check if file is a submodule.
+     *
+     * @param path tested file path
+     * @return {@code true} if the file is a submodule, {@code false} otherwise
+     */
+    public static boolean isSubModule(Path path) {
+        try (BufferedReader reader = new BufferedReader(new FileReader(path.toFile(), StandardCharsets.UTF_8))) {
```
Comment (romain-grecourt) [inline common/common/src/main/java/io/helidon/build/common/FileUtils.java:1153]: That's too specific to be in FileUtils. You can design a method like `containsLine` instead that takes a `Predicate<String>`.

E.g.
```java
public static boolean containsLine(Path path, Predicate<String> predicate) {
    try (Stream<String> lines = Files.lines(path)){
        return lines.anyMatch(predicate);
    } catch (IOException e) {
        throw new UncheckedIOException(e);
    }
}
```

File: maven-plugins/enforcer-maven-plugin/src/main/java/io/helidon/build/maven/enforcer/GitCommands.java [hunk 2]
```diff
@@ -326,7 +333,15 @@ private static GitOperation gitOp(String line) {
         if (line.startsWith("R")) {
             return GitOperation.RENAME;
         }
-
+        if (line.startsWith("T\t")) {
```
Comment (romain-grecourt) [inline maven-plugins/enforcer-maven-plugin/src/main/java/io/helidon/build/maven/enforcer/GitCommands.java:336]: Can you make this logic testable ?

I.e. Separate the process execution and the parsing of its output from the gitTracked method so that we can test the parsing by feeding text to it.

Maybe something like this:

```java
static Map<String, Integer> gitLog(InputStream is) {
    // parsing logic
}
```

**Review by romain-grecourt — APPROVED** [review]
