### PR TITLE
VSCode fixes

### LINKED ISSUE #869: VSCode - Cannot invoke "java.util.Set.stream()"
Exception when trying to get code complete in yaml conf of MP quickstart after `mp.`.

```
[Error - 3:52:10 PM] Request textDocument/completion failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "java.util.Set.stream()" because the return value of "io.helidon.lsp.server.management.MavenSupport.dependencies(String)" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1841)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Set.stream()" because the return value of "io.helidon.lsp.server.management.MavenSupport.dependencies(String)" is null
	at io.helidon.lsp.server.service.config.ConfigurationPropertiesService.metadataForPom(ConfigurationPropertiesService.java:126)
	at io.helidon.lsp.server.service.config.ConfigurationPropertiesService.metadataForFile(ConfigurationPropertiesService.java:557)
	at io.helidon.lsp.server.service.config.yaml.YamlTextDocumentHandler.completion(YamlTextDocumentHandler.java:96)
	at io.helidon.lsp.server.core.HelidonTextDocumentService.lambda$completion$0(HelidonTextDocumentService.java:135)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 6 more

```

### LINKED ISSUE #871: VSCode Helidon:generate fails silently
I installed the vscode plugin, and when I execute the `Helidon: generate a new project` nothing happens. I suspect something is wrong in my environment since I also run into #869.

So there seems to be two issues:
1. Something in my environment is causing the extension to fail -- even though it seems as if I have everything I need
2. The failure is silent. I don't see any errors in View->Output

### PR DESCRIPTION
**Pull request by aserkes**
change docs
add logs
add messages for users
fix NPE

Fixes #869
Fixes #871

### CODE REVIEW

File: ide-support/lsp/lsp-server/src/main/java/io/helidon/lsp/server/management/MavenSupport.java [hunk 1]
```diff
@@ -123,7 +129,11 @@ public Set<Dependency> dependencies(final String pomPath, int timeout) {
                     result = GSON.fromJson(in, new TypeToken<Set<Dependency>>() {
                     }.getType());
                 } catch (IOException e) {
-                    LOGGER.log(Level.SEVERE, "Error when executing the maven command - " + lspMvnDependenciesCommand, e);
+                    String message = "Error when executing the maven command - "
```
Comment (romain-grecourt) [inline ide-support/lsp/lsp-server/src/main/java/io/helidon/lsp/server/management/MavenSupport.java:132]: The normal thing to do here is to propagate the exception as a `UncheckedIOException`, it will be propagated as the cause of an ExecutionException with the `.get()` call below.

File: ide-support/lsp/lsp-server/src/main/java/io/helidon/lsp/server/management/MavenSupport.java [hunk 2]
```diff
@@ -133,7 +143,11 @@ public Set<Dependency> dependencies(final String pomPath, int timeout) {
                 return result;
             }).get(timeout, TimeUnit.MILLISECONDS);
         } catch (Exception e) {
-            LOGGER.log(Level.SEVERE, "Error when executing the maven command - " + lspMvnDependenciesCommand, e);
+            String message = "Error when executing the maven command - " + lspMvnDependenciesCommand
+                    + System.lineSeparator()
+                    + output.content().stream().collect(Collectors.joining(System.lineSeparator()));
```
Comment (romain-grecourt) [inline ide-support/lsp/lsp-server/src/main/java/io/helidon/lsp/server/management/MavenSupport.java:148]: When this method fails to return the dependencies it returns `null` so it's not safe to call without checking for null. Why not return `Set.of()` instead ?

Ideally we would just throw a runtime exception as this is not recoverable.

File: ide-support/lsp/lsp-server/src/main/java/io/helidon/lsp/server/management/MavenSupport.java [hunk 3]
```diff
@@ -145,13 +159,14 @@ public Set<Dependency> dependencies(final String pomPath, int timeout) {
...
         final Properties properties = new Properties();
-        final String corePomProperties = "META-INF/maven/io.helidon.ide-support.lsp/io.helidon.lsp.server/pom.properties";
+        final String corePomProperties = "META-INF/maven/io.helidon.ide-support.lsp/helidon-lsp-server/pom.properties";
 
         try (InputStream in = MavenSupport.class.getClassLoader().getResourceAsStream(corePomProperties)) {
             if (in != null) {
                 properties.load(in);
             }
         } catch (IOException ioe) {
+            LanguageClientLogUtil.logMessage("", ioe);
```
Comment (romain-grecourt) [inline ide-support/lsp/lsp-server/src/main/java/io/helidon/lsp/server/management/MavenSupport.java:169]: What does it mean to return an empty string for the version. Is this a valid use-case that we can't get the resource ? Shouldn't it be just an error instead ? (i.e. throw an exception)

File: ide-support/lsp/lsp-server/src/main/java/io/helidon/lsp/server/service/ContentManager.java [hunk 4]
```diff
@@ -121,7 +124,9 @@ private String createNewTempFile(String fileName) {
             Files.write(tmp, content);
             return tmp.toUri().toString();
         } catch (URISyntaxException | IOException e) {
-            LOGGER.log(Level.SEVERE, "Cannot create temp file for {0}. Exception - {1}", new Object[]{fileName, e.getMessage()});
+            String message = String.format("Cannot create temp file for %s. Exception - %s", fileName, e.getMessage());
```
Comment (romain-grecourt) [inline ide-support/lsp/lsp-server/src/main/java/io/helidon/lsp/server/service/ContentManager.java:127]: Shouldn't these be wrapped with runtime exceptions ?

File: ide-support/lsp/lsp-server/src/main/java/io/helidon/lsp/server/management/MavenSupport.java (hunk 2 above)
Comment (aserkes) [reply ide-support/lsp/lsp-server/src/main/java/io/helidon/lsp/server/management/MavenSupport.java:148]: The value that this method returns is used later in the code and if it is equal to null the farther processing is stopped.

File: ide-support/lsp/lsp-server/src/main/java/io/helidon/lsp/server/management/MavenSupport.java (hunk 3 above)
Comment (aserkes) [reply ide-support/lsp/lsp-server/src/main/java/io/helidon/lsp/server/management/MavenSupport.java:169]: In this case it will try to use the latest version of the maven plugin

File: ide-support/lsp/lsp-server/src/main/java/io/helidon/lsp/server/service/ContentManager.java (hunk 4 above)
Comment (aserkes) [reply ide-support/lsp/lsp-server/src/main/java/io/helidon/lsp/server/service/ContentManager.java:127]: Why do we need to throw a runtime exception? The problem will be logged and the user will see the message about it in VSCode.

**Review by romain-grecourt — APPROVED** [review]
